name: ai_meal_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.0.0
  flutter_slidable: ^4.0.3
  flutter_timezone: ^5.0.1
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
